server:
  port: ${BACKEND_DISCOVERY_SERVICE_PORT_INT}
  # ssl:
  #   key-store: /${BACKEND_DISCOVERY_SERVICE_HTTPS_KEY_STORE}
  #   key-store-password: ${BACKEND_DISCOVERY_SERVICE_HTTPS_KEY_STORE_PASSWORD}
  #   keyStoreType: PKCS12
  #   keyAlias: ${BACKEND_DISCOVERY_SERVICE_HTTPS_KEY_STORE_ALIAS}
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${BACKEND_DISCOVERY_SERVICE_HOSTNAME}:${BACKEND_DISCOVERY_SERVICE_PORT_INT}/eureka
