version: "3.8"
secrets:
  SECURITY_SERVICES_SHARED_KEY:
    external: true
  SECURITY_JWT_SECRET_KEY:
    external: true
  SECURITY_JWT_CLAIMS_KEY_ROLES:
    external: true
  SECURITY_TRUST_STORE_PASSWORD:
    external: true
  SECURITY_TRUST_STORE_ALIAS:
    external: true
  DB_LOCAL_TEST_SERVICE_USER:
    external: true
  DB_LOCAL_TEST_SERVICE_PASSWORD:
    external: true
  DB_AUTHENTICATION_SERVICE_USER:
    external: true
  DB_AUTHENTICATION_SERVICE_PASSWORD:
    external: true
  DB_DIRECTORY_SERVICE_USER:
    external: true
  DB_DIRECTORY_SERVICE_PASSWORD:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_USERNAME:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD:
    external: true
  BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
# +-----------------------------------------------------------------------------+
# | Services section                                                            |
# +-----------------------------------------------------------------------------+
services:
  # +---------------------------------------------------------------------------+
  # | Database containers section (mask: 10.200.1.64/26)                        |
  # +---------------------------------------------------------------------------+
  postgres-procom-erp-authentication-service:
    container_name: ${DB_AUTHENTICATION_SERVICE_HOSTNAME}
    hostname: ${DB_AUTHENTICATION_SERVICE_HOSTNAME}
    image: postgres:13
    environment:
      POSTGRES_USER: /run/secrets/DB_AUTHENTICATION_SERVICE_USER
      POSTGRES_PASSWORD: /run/secrets/DB_AUTHENTICATION_SERVICE_PASSWORD
      POSTGRES_DB: ${DB_AUTHENTICATION_SERVICE_DB}
    secrets:
      - DB_AUTHENTICATION_SERVICE_USER
      - DB_AUTHENTICATION_SERVICE_PASSWORD
    expose:
      - "${DB_AUTHENTICATION_SERVICE_PORT_INT}"
    ports:
      - "${DB_AUTHENTICATION_SERVICE_PORT_EXT}:${DB_AUTHENTICATION_SERVICE_PORT_INT}"
    networks:
      vnet-procom-erp:
        ipv4_address: ${DB_AUTHENTICATION_SERVICE_IP_INT}
    volumes:
      - db-procom-erp-authentication-service-data:/var/lib/postgresql/data
      - ${DB_AUTHENTICATION_SERVICE_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DB_AUTHENTICATION_SERVICE_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  # +-----------------------------------------------------------------------------+

  postgres-procom-erp-directory-service:
    container_name: ${DB_DIRECTORY_SERVICE_HOSTNAME}
    hostname: ${DB_DIRECTORY_SERVICE_HOSTNAME}
    image: postgres:13
    environment:
      POSTGRES_USER: /run/secrets/DB_DIRECTORY_SERVICE_USER
      POSTGRES_PASSWORD: /run/secrets/DB_DIRECTORY_SERVICE_PASSWORD
      POSTGRES_DB: ${DB_DIRECTORY_SERVICE_DB}
    secrets:
      - DB_DIRECTORY_SERVICE_USER
      - DB_DIRECTORY_SERVICE_PASSWORD
    expose:
      - "${DB_DIRECTORY_SERVICE_PORT_INT}"
    ports:
      - "${DB_DIRECTORY_SERVICE_PORT_EXT}:${DB_DIRECTORY_SERVICE_PORT_INT}"
    networks:
      vnet-procom-erp:
        ipv4_address: ${DB_DIRECTORY_SERVICE_IP_INT}
    volumes:
      - db-procom-erp-directory-service-data:/var/lib/postgresql/data
      - ${DB_DIRECTORY_SERVICE_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DB_DIRECTORY_SERVICE_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  # +-----------------------------------------------------------------------------+

  #  postgres-procom-erp-local-test-service:
  #    container_name: ${DB_LOCAL_TEST_SERVICE_HOSTNAME}
  #    hostname: ${DB_LOCAL_TEST_SERVICE_HOSTNAME}
  #    image: postgres:13
  #    environment:
  #      POSTGRES_USER: ${DB_LOCAL_TEST_SERVICE_USER}
  #      POSTGRES_PASSWORD: ${DB_LOCAL_TEST_SERVICE_PASSWORD}
  #      POSTGRES_DB: ${DB_LOCAL_TEST_SERVICE_DB}
  #    expose:
  #      - "${DB_LOCAL_TEST_SERVICE_PORT_INT}"
  #    ports:
  #      - "${DB_LOCAL_TEST_SERVICE_PORT_EXT}:${DB_LOCAL_TEST_SERVICE_PORT_INT}"
  #    networks:
  #      vnet-procom-erp:
  #        ipv4_address: ${DB_LOCAL_TEST_SERVICE_IP_INT}
  #    volumes:
  #      - db-procom-erp-local-test-service-data:/var/lib/postgresql/data
  #      - ${DB_LOCAL_TEST_SERVICE_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
  #      - ${DB_LOCAL_TEST_SERVICE_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf
  #    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  # +---------------------------------------------------------------------------+
  # | Backend containers section (mask: 10.200.1.128/26)                        |
  # +---------------------------------------------------------------------------+

  springboot-procom-erp-message-broker-service:
    container_name: ${BACKEND_MESSAGE_BROKER_SERVICE_HOSTNAME}
    hostname: ${BACKEND_MESSAGE_BROKER_SERVICE_HOSTNAME}
    image: "rabbitmq:3-management"
    ports:
      - "${BACKEND_MESSAGE_BROKER_SERVICE_PORT_EXT}:${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}"
      - "${BACKEND_MESSAGE_BROKER_SERVICE_ADMIN_PORT_EXT}:${BACKEND_MESSAGE_BROKER_SERVICE_ADMIN_PORT_INT}"
    env_file: ./.env
    secrets:
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_MESSAGE_BROKER_SERVICE_IP_INT}
    volumes:
      - ${BACKEND_MESSAGE_BROKER_SERVICE_PATH}/config/rabbitmq.conf:/${RABBIT_MQ_CONFIG}
      - ${SYSTEM_PATH}:/etc/rabbitmq/CA
      - ${BACKEND_MESSAGE_BROKER_SERVICE_PATH}/message-broker-service-certificate.pem:/etc/rabbitmq/certs/message-broker-service-certificate.pem
      - ${BACKEND_MESSAGE_BROKER_SERVICE_PATH}/message-broker-service-key.pem:/etc/rabbitmq/certs/message-broker-service-key.pem

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-gateway-service:
    container_name: ${BACKEND_GATEWAY_SERVICE_HOSTNAME}
    hostname: ${BACKEND_GATEWAY_SERVICE_HOSTNAME}
    image: ${JAVA_IMAGE}
    expose:
      - ${BACKEND_GATEWAY_SERVICE_PORT_INT}
    entrypoint: ${ENTRYPOINT}
    ports:
      - "${BACKEND_GATEWAY_SERVICE_PORT_EXT}:${BACKEND_GATEWAY_SERVICE_PORT_INT}"
    env_file: ./.env
    secrets:
      - BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_GATEWAY_SERVICE_IP_INT}
    volumes:
      - ${BACKEND_GATEWAY_SERVICE_PATH}/target:/app
      - ${BACKEND_GATEWAY_SERVICE_PATH}/gateway-service-keystore.p12:/certs/gateway-service-keystore.p12
      - ${SYSTEM_PATH}/../security:/certs/all
      - ${SYSTEM_PATH}:/config

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-authentication-service:
    container_name: ${BACKEND_AUTHENTICATION_SERVICE_HOSTNAME}
    hostname: ${BACKEND_AUTHENTICATION_SERVICE_HOSTNAME}
    build:
      context: ${BACKEND_AUTHENTICATION_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_IMAGE: ${JAVA_IMAGE}
        BACKEND_AUTHENTICATION_SERVICE_PORT_INT: ${BACKEND_AUTHENTICATION_SERVICE_PORT_INT}
        ENTRYPOINT: ${ENTRYPOINT}
        BACKEND_MESSAGE_BROKER_SERVICE_IP_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_IP_INT}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
    image: ${JAVA_IMAGE}
    entrypoint: ${ENTRYPOINT}
    expose:
      - ${BACKEND_AUTHENTICATION_SERVICE_PORT_INT}
    env_file: ./.env
    secrets:
      - DB_AUTHENTICATION_SERVICE_USER
      - DB_AUTHENTICATION_SERVICE_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    depends_on:
      - "postgres-procom-erp-authentication-service"
      - "springboot-procom-erp-message-broker-service"
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_AUTHENTICATION_SERVICE_IP_INT}

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-directory-service:
    container_name: ${BACKEND_DIRECTORY_SERVICE_HOSTNAME}
    hostname: ${BACKEND_DIRECTORY_SERVICE_HOSTNAME}
    image: ${JAVA_IMAGE}
    expose:
      - ${BACKEND_DIRECTORY_SERVICE_PORT_INT}
    entrypoint: ${ENTRYPOINT}
    env_file: ./.env
    secrets:
      - DB_DIRECTORY_SERVICE_USER
      - DB_DIRECTORY_SERVICE_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
    depends_on:
      - "postgres-procom-erp-directory-service"
      - "springboot-procom-erp-message-broker-service"
      - "springboot-procom-erp-authentication-service"
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_DIRECTORY_SERVICE_IP_INT}
    volumes:
      - ${BACKEND_DIRECTORY_SERVICE_PATH}/target:/app
      - ${BACKEND_DIRECTORY_SERVICE_PATH}/directory-service-keystore.p12:/certs/directory-service-keystore.p12
      - ${SYSTEM_PATH}:/config

  # +---------------------------------------------------------------------------+
  # | Frontend containers section (mask: 10.200.1.192/26)                       |
  # +---------------------------------------------------------------------------+

# +-----------------------------------------------------------------------------+
# | Networks section                                                            |
# +-----------------------------------------------------------------------------+
networks:
  vnet-procom-erp:
    driver: overlay
    ipam:
      config:
        - subnet: ${NETWORK_PROCOM_ERP}

volumes:
  db-procom-erp-authentication-service-data:
  db-procom-erp-directory-service-data:
  #db-procom-erp-local-test-service-data:
