version: "3.8"

# +-----------------------------------------------------------------------------+
# | Services section                                                            |
# +-----------------------------------------------------------------------------+
services:

  # +---------------------------------------------------------------------------+
  # | Database containers section (mask: 10.200.1.64/26)                        |
  # +---------------------------------------------------------------------------+
  postgres-procom-erp-auth-service:
    container_name: ${DB_AUTH_SERVICE_HOSTNAME}
    hostname: ${DB_AUTH_SERVICE_HOSTNAME}
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_AUTH_SERVICE_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_SERVICE_PASSWORD}
      POSTGRES_DB: ${DB_AUTH_SERVICE_DB}
    expose:
      - "${DB_AUTH_SERVICE_PORT_INT}"
    ports:
      - "${DB_AUTH_SERVICE_PORT_EXT}:${DB_AUTH_SERVICE_PORT_INT}"
    networks:
      vnet-procom-erp:
        ipv4_address: ${DB_AUTH_SERVICE_IP_INT}
    volumes:
      - db-procom-erp-auth-service-data:/var/lib/postgresql/data
      - ${DB_AUTH_SERVICE_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DB_AUTH_SERVICE_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  # +---------------------------------------------------------------------------+

  postgres-procom-erp-dir-service:
    container_name: ${DB_DIR_SERVICE_HOSTNAME}
    hostname: ${DB_DIR_SERVICE_HOSTNAME}
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_DIR_SERVICE_USER}
      POSTGRES_PASSWORD: ${DB_DIR_SERVICE_PASSWORD}
      POSTGRES_DB: ${DB_DIR_SERVICE_DB}
    expose:
      - "${DB_DIR_SERVICE_PORT_INT}"
    ports:
      - "${DB_DIR_SERVICE_PORT_EXT}:${DB_DIR_SERVICE_PORT_INT}"
    networks:
      vnet-procom-erp:
        ipv4_address: ${DB_DIR_SERVICE_IP_INT}
    volumes:
      - db-procom-erp-dir-service-data:/var/lib/postgresql/data
      - ${DB_DIR_SERVICE_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DB_DIR_SERVICE_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'


  # +---------------------------------------------------------------------------+
  # | Backend containers section (mask: 10.200.1.128/26)                        |
  # +---------------------------------------------------------------------------+
  springboot-procom-erp-auth-service:
    container_name: ${BACKEND_AUTH_SERVICE_HOSTNAME}
    hostname: ${BACKEND_AUTH_SERVICE_HOSTNAME}
    build:
      context: ${BACKEND_AUTH_SERVICE_PATH}
      dockerfile: ./Dockerfile
    ports:
      - "${BACKEND_AUTH_SERVICE_PORT_EXT}:${BACKEND_AUTH_SERVICE_PORT_INT}"
    env_file: ./.env
    depends_on:
      - "postgres-procom-erp-auth-service"
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_AUTH_SERVICE_IP_INT}
    volumes:
      - ${BACKEND_AUTH_SERVICE_PATH}/target:/app

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-dir-service:
    container_name: ${BACKEND_DIR_SERVICE_HOSTNAME}
    hostname: ${BACKEND_DIR_SERVICE_HOSTNAME}
    build:
      context: ${BACKEND_DIR_SERVICE_PATH}
      dockerfile: ./Dockerfile
    ports:
      - "${BACKEND_DIR_SERVICE_PORT_EXT}:${BACKEND_DIR_SERVICE_PORT_INT}"
    env_file: ./.env
    depends_on:
      - "postgres-procom-erp-dir-service"
    networks:
      vnet-procom-erp:
        ipv4_address: ${BACKEND_DIR_SERVICE_IP_INT}
    volumes:
      - ${BACKEND_DIR_SERVICE_PATH}/target:/app


  # +---------------------------------------------------------------------------+
  # | Frontend containers section (mask: 10.200.1.192/26)                       |
  # +---------------------------------------------------------------------------+


# +-----------------------------------------------------------------------------+
# | Networks section                                                            |
# +-----------------------------------------------------------------------------+
networks:
  vnet-procom-erp:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_PROCOM_ERP}

volumes:
  db-procom-erp-auth-service-data:
  db-procom-erp-dir-service-data:
