version: "3.8"

# +-----------------------------------------------------------------------------+
# | Secrets section                                                             |
# +-----------------------------------------------------------------------------+

secrets:
  SECURITY_SERVICES_SHARED_KEY:
    external: true
  SECURITY_JWT_SECRET_KEY:
    external: true
  SECURITY_JWT_CLAIMS_KEY_ROLES:
    external: true
  SECURITY_TRUST_STORE_PASSWORD:
    external: true
  SECURITY_TRUST_STORE_ALIAS:
    external: true
  BACKEND_MAIL_USERNAME:
    external: true
  BACKEND_MAIL_PASSWORD:
    external: true
  DB_LOCAL_TEST_SERVICE_USER:
    external: true
  DB_LOCAL_TEST_SERVICE_PASSWORD:
    external: true
  DB_AUTHENTICATION_SERVICE_USER:
    external: true
  DB_AUTHENTICATION_SERVICE_PASSWORD:
    external: true
  DB_DIRECTORY_SERVICE_USER:
    external: true
  DB_DIRECTORY_SERVICE_PASSWORD:
    external: true
  DB_INVENTORY_SERVICE_USER:
    external: true
  DB_INVENTORY_SERVICE_PASSWORD:
    external: true
  DB_ORDER_SERVICE_USER:
    external: true
  DB_ORDER_SERVICE_PASSWORD:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_USERNAME:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD:
    external: true
  BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_MESSAGE_BROKER_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_INVENTORY_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_INVENTORY_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  BACKEND_ORDER_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  BACKEND_ORDER_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true
  FRONTEND_WEBAPP_SERVICE_HTTPS_KEY_STORE_ALIAS:
    external: true
  FRONTEND_WEBAPP_SERVICE_HTTPS_KEY_STORE_PASSWORD:
    external: true

# +-----------------------------------------------------------------------------+
# | Services section                                                            |
# +-----------------------------------------------------------------------------+

services:
  # +---------------------------------------------------------------------------+
  # | Database section                                                          |
  # +---------------------------------------------------------------------------+

  postgres-procom-erp-authentication-service:
    image: ${DB_AUTHENTICATION_SERVICE_HOSTNAME}:${DB_AUTHENTICATION_SERVICE_IMAGE_VERSION}
    build:
      context: ${DB_AUTHENTICATION_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        DB_IMAGE: ${DB_IMAGE}
        ENTRYPOINT: ${DB_ENTRYPOINT}
    hostname: ${DB_AUTHENTICATION_SERVICE_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_AUTHENTICATION_SERVICE_DB}
    secrets:
      - DB_AUTHENTICATION_SERVICE_USER
      - DB_AUTHENTICATION_SERVICE_PASSWORD
    ports:
      - "${DB_AUTHENTICATION_SERVICE_PORT_EXT}:${DB_AUTHENTICATION_SERVICE_PORT_INT}"
    volumes:
      - db-procom-erp-authentication-service-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp
    command: -c 'port=${DB_AUTHENTICATION_SERVICE_PORT_INT}'

  # +-----------------------------------------------------------------------------+

  postgres-procom-erp-directory-service:
    image: ${DB_DIRECTORY_SERVICE_HOSTNAME}:${DB_DIRECTORY_SERVICE_IMAGE_VERSION}
    build:
      context: ${DB_DIRECTORY_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        DB_IMAGE: ${DB_IMAGE}
        ENTRYPOINT: ${DB_ENTRYPOINT}
    hostname: ${DB_DIRECTORY_SERVICE_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_DIRECTORY_SERVICE_DB}
    secrets:
      - DB_DIRECTORY_SERVICE_USER
      - DB_DIRECTORY_SERVICE_PASSWORD
    ports:
      - "${DB_DIRECTORY_SERVICE_PORT_EXT}:${DB_DIRECTORY_SERVICE_PORT_INT}"
    volumes:
      - db-procom-erp-directory-service-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp
    command: -c 'port=${DB_DIRECTORY_SERVICE_PORT_INT}'

  # +-----------------------------------------------------------------------------+

  postgres-procom-erp-inventory-service:
    image: ${DB_INVENTORY_SERVICE_HOSTNAME}:${DB_INVENTORY_SERVICE_IMAGE_VERSION}
    build:
      context: ${DB_INVENTORY_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        DB_IMAGE: ${DB_IMAGE}
        ENTRYPOINT: ${DB_ENTRYPOINT}
    environment:
      POSTGRES_DB: ${DB_INVENTORY_SERVICE_DB}
    hostname: ${DB_INVENTORY_SERVICE_HOSTNAME}
    secrets:
      - DB_INVENTORY_SERVICE_USER
      - DB_INVENTORY_SERVICE_PASSWORD
    ports:
      - "${DB_INVENTORY_SERVICE_PORT_EXT}:${DB_INVENTORY_SERVICE_PORT_INT}"
    volumes:
      - db-procom-erp-inventory-service-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp
    command: -c 'port=${DB_INVENTORY_SERVICE_PORT_INT}'

  # +-----------------------------------------------------------------------------+

  postgres-procom-erp-order-service:
    image: ${DB_ORDER_SERVICE_HOSTNAME}:${DB_ORDER_SERVICE_IMAGE_VERSION}
    build:
      context: ${DB_ORDER_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        DB_IMAGE: ${DB_IMAGE}
    hostname: ${DB_ORDER_SERVICE_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_ORDER_SERVICE_DB}
    secrets:
      - DB_ORDER_SERVICE_USER
      - DB_ORDER_SERVICE_PASSWORD
    ports:
      - "${DB_ORDER_SERVICE_PORT_EXT}:${DB_ORDER_SERVICE_PORT_INT}"
    volumes:
      - db-procom-erp-order-service-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp
    command: -c 'port=${DB_ORDER_SERVICE_PORT_INT}'

  # +---------------------------------------------------------------------------+
  # | Backend containers section                                                |
  # +---------------------------------------------------------------------------+

  springboot-procom-erp-message-broker-service:
    image: ${BACKEND_MESSAGE_BROKER_SERVICE_HOSTNAME}:${BACKEND_MESSAGE_BROKER_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_MESSAGE_BROKER_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        RABBIT_MQ_IMAGE: ${RABBIT_MQ_IMAGE}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
    hostname: ${BACKEND_MESSAGE_BROKER_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    ports:
      - "${BACKEND_MESSAGE_BROKER_SERVICE_PORT_EXT}:${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}"
      - "${BACKEND_MESSAGE_BROKER_SERVICE_ADMIN_PORT_EXT}:${BACKEND_MESSAGE_BROKER_SERVICE_ADMIN_PORT_INT}"
    volumes:
      - procom-erp-message-broker-service-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-gateway-service:
    image: ${BACKEND_GATEWAY_SERVICE_HOSTNAME}:${BACKEND_GATEWAY_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_GATEWAY_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_BUILD_IMAGE: ${JAVA_BUILD_IMAGE}
        JAVA_IMAGE: ${JAVA_IMAGE}
        MAVEN_JAVA_VERSION: ${MAVEN_JAVA_VERSION}
        BACKEND_GATEWAY_SERVICE_IMAGE_VERSION: ${BACKEND_GATEWAY_SERVICE_IMAGE_VERSION}
        MAVEN_SPRING_BOOT_VERSION: ${MAVEN_SPRING_BOOT_VERSION}
        MAVEN_SPRING_CLOUD_VERSION: ${MAVEN_SPRING_CLOUD_VERSION}
        BACKEND_GATEWAY_SERVICE_PORT_INT: ${BACKEND_GATEWAY_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
        ENTRYPOINT: ${ENTRYPOINT}
    hostname: ${BACKEND_GATEWAY_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_JWT_CLAIMS_KEY_ROLES
      - SECURITY_SERVICES_SHARED_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    ports:
      - "${BACKEND_GATEWAY_SERVICE_PORT_EXT}:${BACKEND_GATEWAY_SERVICE_PORT_INT}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-authentication-service:
    image: ${BACKEND_AUTHENTICATION_SERVICE_HOSTNAME}:${BACKEND_AUTHENTICATION_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_AUTHENTICATION_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_BUILD_IMAGE: ${JAVA_BUILD_IMAGE}
        JAVA_IMAGE: ${JAVA_IMAGE}
        MAVEN_JAVA_VERSION: ${MAVEN_JAVA_VERSION}
        BACKEND_AUTHENTICATION_SERVICE_IMAGE_VERSION: ${BACKEND_AUTHENTICATION_SERVICE_IMAGE_VERSION}
        MAVEN_SPRING_BOOT_VERSION: ${MAVEN_SPRING_BOOT_VERSION}
        MAVEN_SPRINGDOC_OPENAPI_VERSION: ${MAVEN_SPRINGDOC_OPENAPI_VERSION}
        MAVEN_APACHE_HTTP_VERSION: ${MAVEN_APACHE_HTTP_VERSION}
        MAVEN_AMQP_VERSION: ${MAVEN_AMQP_VERSION}
        MAVEN_POSTGRESQL_VERSION: ${MAVEN_POSTGRESQL_VERSION}
        MAVEN_LOMBOK_VERSION: ${MAVEN_LOMBOK_VERSION}
        MAVEN_SPRING_SECURITY_TEST_VERSION: ${MAVEN_SPRING_SECURITY_TEST_VERSION}
        BACKEND_AUTHENTICATION_SERVICE_PORT_INT: ${BACKEND_AUTHENTICATION_SERVICE_PORT_INT}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
        ENTRYPOINT: ${ENTRYPOINT}
    hostname: ${BACKEND_AUTHENTICATION_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - DB_AUTHENTICATION_SERVICE_USER
      - DB_AUTHENTICATION_SERVICE_PASSWORD
      - BACKEND_MAIL_USERNAME
      - BACKEND_MAIL_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_AUTHENTICATION_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_JWT_CLAIMS_KEY_ROLES
      - SECURITY_SERVICES_SHARED_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    ports:
      - "${BACKEND_AUTHENTICATION_SERVICE_PORT_EXT}:${BACKEND_AUTHENTICATION_SERVICE_PORT_INT}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-directory-service:
    image: ${BACKEND_DIRECTORY_SERVICE_HOSTNAME}:${BACKEND_DIRECTORY_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_DIRECTORY_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_BUILD_IMAGE: ${JAVA_BUILD_IMAGE}
        JAVA_IMAGE: ${JAVA_IMAGE}
        MAVEN_JAVA_VERSION: ${MAVEN_JAVA_VERSION}
        BACKEND_DIRECTORY_SERVICE_IMAGE_VERSION: ${BACKEND_DIRECTORY_SERVICE_IMAGE_VERSION}
        MAVEN_SPRING_BOOT_VERSION: ${MAVEN_SPRING_BOOT_VERSION}
        MAVEN_SPRINGDOC_OPENAPI_VERSION: ${MAVEN_SPRINGDOC_OPENAPI_VERSION}
        MAVEN_APACHE_HTTP_VERSION: ${MAVEN_APACHE_HTTP_VERSION}
        MAVEN_AMQP_VERSION: ${MAVEN_AMQP_VERSION}
        MAVEN_POSTGRESQL_VERSION: ${MAVEN_POSTGRESQL_VERSION}
        MAVEN_LOMBOK_VERSION: ${MAVEN_LOMBOK_VERSION}
        MAVEN_SPRING_SECURITY_TEST_VERSION: ${MAVEN_SPRING_SECURITY_TEST_VERSION}
        BACKEND_DIRECTORY_SERVICE_PORT_INT: ${BACKEND_DIRECTORY_SERVICE_PORT_INT}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
        ENTRYPOINT: ${ENTRYPOINT}
    hostname: ${BACKEND_DIRECTORY_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - DB_DIRECTORY_SERVICE_USER
      - DB_DIRECTORY_SERVICE_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_DIRECTORY_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_JWT_CLAIMS_KEY_ROLES
      - SECURITY_SERVICES_SHARED_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-order-service:
    image: ${BACKEND_ORDER_SERVICE_HOSTNAME}:${BACKEND_ORDER_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_ORDER_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_BUILD_IMAGE: ${JAVA_BUILD_IMAGE}
        JAVA_IMAGE: ${JAVA_IMAGE}
        MAVEN_JAVA_VERSION: ${MAVEN_JAVA_VERSION}
        BACKEND_ORDER_SERVICE_IMAGE_VERSION: ${BACKEND_ORDER_SERVICE_IMAGE_VERSION}
        MAVEN_SPRING_BOOT_VERSION: ${MAVEN_SPRING_BOOT_VERSION}
        MAVEN_SPRINGDOC_OPENAPI_VERSION: ${MAVEN_SPRINGDOC_OPENAPI_VERSION}
        MAVEN_APACHE_HTTP_VERSION: ${MAVEN_APACHE_HTTP_VERSION}
        MAVEN_AMQP_VERSION: ${MAVEN_AMQP_VERSION}
        MAVEN_POSTGRESQL_VERSION: ${MAVEN_POSTGRESQL_VERSION}
        MAVEN_LOMBOK_VERSION: ${MAVEN_LOMBOK_VERSION}
        MAVEN_SPRING_SECURITY_TEST_VERSION: ${MAVEN_SPRING_SECURITY_TEST_VERSION}
        BACKEND_ORDER_SERVICE_PORT_INT: ${BACKEND_ORDER_SERVICE_PORT_INT}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
        ENTRYPOINT: ${ENTRYPOINT}
    hostname: ${BACKEND_ORDER_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - DB_ORDER_SERVICE_USER
      - DB_ORDER_SERVICE_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_ORDER_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_ORDER_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_JWT_CLAIMS_KEY_ROLES
      - SECURITY_SERVICES_SHARED_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+

  springboot-procom-erp-inventory-service:
    image: ${BACKEND_INVENTORY_SERVICE_HOSTNAME}:${BACKEND_INVENTORY_SERVICE_IMAGE_VERSION}
    build:
      context: ${BACKEND_INVENTORY_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        JAVA_BUILD_IMAGE: ${JAVA_BUILD_IMAGE}
        JAVA_IMAGE: ${JAVA_IMAGE}
        MAVEN_JAVA_VERSION: ${MAVEN_JAVA_VERSION}
        BACKEND_INVENTORY_SERVICE_IMAGE_VERSION: ${BACKEND_INVENTORY_SERVICE_IMAGE_VERSION}
        MAVEN_SPRING_BOOT_VERSION: ${MAVEN_SPRING_BOOT_VERSION}
        MAVEN_SPRINGDOC_OPENAPI_VERSION: ${MAVEN_SPRINGDOC_OPENAPI_VERSION}
        MAVEN_APACHE_HTTP_VERSION: ${MAVEN_APACHE_HTTP_VERSION}
        MAVEN_AMQP_VERSION: ${MAVEN_AMQP_VERSION}
        MAVEN_POSTGRESQL_VERSION: ${MAVEN_POSTGRESQL_VERSION}
        MAVEN_LOMBOK_VERSION: ${MAVEN_LOMBOK_VERSION}
        MAVEN_SPRING_SECURITY_TEST_VERSION: ${MAVEN_SPRING_SECURITY_TEST_VERSION}
        BACKEND_INVENTORY_SERVICE_PORT_INT: ${BACKEND_INVENTORY_SERVICE_PORT_INT}
        BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT: ${BACKEND_MESSAGE_BROKER_SERVICE_PORT_INT}
        SECURITY_TRUST_STORE_PATH: ${SECURITY_TRUST_STORE_PATH}
        ENTRYPOINT: ${ENTRYPOINT}
    hostname: ${BACKEND_INVENTORY_SERVICE_HOSTNAME}
    env_file: ./.env
    secrets:
      - DB_INVENTORY_SERVICE_USER
      - DB_INVENTORY_SERVICE_PASSWORD
      - BACKEND_MESSAGE_BROKER_SERVICE_USERNAME
      - BACKEND_MESSAGE_BROKER_SERVICE_PASSWORD
      - BACKEND_INVENTORY_SERVICE_HTTPS_KEY_STORE_ALIAS
      - BACKEND_INVENTORY_SERVICE_HTTPS_KEY_STORE_PASSWORD
      - SECURITY_JWT_SECRET_KEY
      - SECURITY_JWT_CLAIMS_KEY_ROLES
      - SECURITY_SERVICES_SHARED_KEY
      - SECURITY_TRUST_STORE_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

  # +---------------------------------------------------------------------------+
  # | Frontend containers section                                               |
  # +---------------------------------------------------------------------------+

  react-procom-erp-webapp-service:
    image: ${FRONTEND_WEBAPP_SERVICE_HOSTNAME}:${FRONTEND_WEBAPP_SERVICE_IMAGE_VERSION}
    build:
      context: ${FRONTEND_WEBAPP_SERVICE_PATH}
      dockerfile: Dockerfile
      args:
        FRONT_BUILD_IMAGE: ${FRONT_BUILD_IMAGE}
        FRONT_IMAGE: ${FRONT_IMAGE}
    hostname: ${FRONTEND_WEBAPP_SERVICE_HOSTNAME}
    environment:
      FRONTEND_WEBAPP_SERVICE_PORT_INT: ${FRONTEND_WEBAPP_SERVICE_PORT_INT}
    secrets:
      - FRONTEND_WEBAPP_SERVICE_HTTPS_KEY_STORE_ALIAS
      - FRONTEND_WEBAPP_SERVICE_HTTPS_KEY_STORE_PASSWORD
    ports:
      - ${FRONTEND_WEBAPP_SERVICE_PORT_INT}:${FRONTEND_WEBAPP_SERVICE_PORT_EXT}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - vnet-procom-erp

# +-----------------------------------------------------------------------------+
# | Networks section                                                            |
# +-----------------------------------------------------------------------------+

networks:
  vnet-procom-erp:
    driver: overlay

# +-----------------------------------------------------------------------------+
# | Volumes  section                                                            |
# +-----------------------------------------------------------------------------+

volumes:
  db-procom-erp-authentication-service-data:
  db-procom-erp-directory-service-data:
  db-procom-erp-inventory-service-data:
  db-procom-erp-order-service-data:
  procom-erp-message-broker-service-data:
