spring:
  application:
    name: ${BACKEND_GATEWAY_SERVICE_HOSTNAME}
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://${BACKEND_AUTH_SERVICE_IP_INT}:${BACKEND_AUTH_SERVICE_PORT_INT}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/$\{segment}
  security:
    require-ssl: false

server:
  port: ${BACKEND_GATEWAY_SERVICE_PORT_EXT}
  # ssl:
  #   key-store: /${BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE}
  #   key-store-password: ${BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD}
  #   keyStoreType: PKCS12
  #   keyAlias: ${BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_ALIAS}
  #   trust-store: /${BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE}
  #   trust-store-password: ${BACKEND_GATEWAY_SERVICE_HTTPS_KEY_STORE_PASSWORD}
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://${BACKEND_DISCOVERY_SERVICE_HOSTNAME}:${BACKEND_DISCOVERY_SERVICE_PORT_INT}/eureka
